#
# mappings.yml - mappings to nagios configuration templates
#

# default mapping, applies to unknown clusters (required)
default:
  desc: Generic linux server
  template: default

# example: web cluster mappings (prod. and staging)
web.prod:
  desc: Production web server
  template: web

db.mongo.prod:
  desc: Production mongodb server
  template: mongodb
